name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Build docs site
      with:
        node-version: '10.x'
        java-version: '8.x'
        architecture: x64
    - run: |
        sudo npm install -g
        npm run pretsdocs
        npm run tsdocs
        npm run docs:build
        npm run docs:publish
        
