name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10.x]
        java: [8.x]
    steps:
    - name: SetUp node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: SetUp java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
        architecture: x64
    - name: Build docs site
      run: |
        sudo npm install -g
        npm run pretsdocs
        npm run tsdocs
        npm run docs:build
        npm run docs:publish
        
