name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    - name: Build docs site
      uses: actions/checkout@v1
    - run: |
        sudo npm install -g npm
        sudo npm install -g
        npm run pretsdocs
        npm run tsdocs
        npm run docs:build
        npm run docs:publish
        
