name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: build website
      with:
        node-version: '10.x'
        java-version: '8.x'
        architecture: x64
      run: |
        sudo npm install -g
        npm run pretsdocs
        npm run tsdocs
        npm run docs:build
        npm run docs:publish
        
